### ISSUE TITLE
stylesheet

### ISSUE THREAD

**Issue by hrh5775** [Nepomuk1999/ConcertMaster#11]
**in composition pages**

/usr/lib/jvm/default-java/bin/java -javaagent:/opt/google/own/InteliJ/lib/idea_rt.jar=41181:/opt/google/own/InteliJ/bin -Dfile.encoding=UTF-8 -classpath "/usr/lib/jvm/default-java/jre/lib/charsets.jar:/usr/lib/jvm/default-java/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/default-java/jre/lib/ext/dnsns.jar:/usr/lib/jvm/default-java/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/default-java/jre/lib/ext/jaccess.jar:/usr/lib/jvm/default-java/jre/lib/ext/java-atk-wrapper.jar:/usr/lib/jvm/default-java/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/default-java/jre/lib/ext/localedata.jar:/usr/lib/jvm/default-java/jre/lib/ext/nashorn.jar:/usr/lib/jvm/default-java/jre/lib/ext/sunec.jar:/usr/lib/jvm/default-java/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/default-java/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/default-java/jre/lib/ext/zipfs.jar:/usr/lib/jvm/default-java/jre/lib/jce.jar:/usr/lib/jvm/default-java/jre/lib/jfxswt.jar:/usr/lib/jvm/default-java/jre/lib/jsse.jar:/usr/lib/jvm/default-java/jre/lib/management-agent.jar:/usr/lib/jvm/default-java/jre/lib/resources.jar:/usr/lib/jvm/default-java/jre/lib/rt.jar:/usr/lib/jvm/default-java/lib/ant-javafx.jar:/usr/lib/jvm/default-java/lib/dt.jar:/usr/lib/jvm/default-java/lib/javafx-mx.jar:/usr/lib/jvm/default-java/lib/jconsole.jar:/usr/lib/jvm/default-java/lib/sa-jdi.jar:/usr/lib/jvm/default-java/lib/tools.jar:/media/Data/Schule/FHV/Semester 4/Objektorientierte Analyse und Design/Projekt/other/ConcertMaster/Client/target/classes:/home/helmut/.m2/repository/com/teamdev/jxbrowser/jxbrowser-win/6.13/jxbrowser-win-6.13.jar:/home/helmut/.m2/repository/com/teamdev/jxbrowser/jxbrowser/6.13/jxbrowser-6.13.jar:/home/helmut/.m2/repository/com/teamdev/jxbrowser/jxbrowser-linux32/6.13/jxbrowser-linux32-6.13.jar:/home/helmut/.m2/repository/com/teamdev/jxbrowser/jxbrowser-linux64/6.13/jxbrowser-linux64-6.13.jar:/home/helmut/.m2/repository/com/teamdev/jxbrowser/jxbrowser-mac/6.13/jxbrowser-mac-6.13.jar:/media/Data/Schule/FHV/Semester 4/Objektorientierte Analyse und Design/Projekt/other/ConcertMaster/JSONConnector/target/classes:/home/helmut/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.0.pr3/jackson-databind-2.9.0.pr3.jar:/home/helmut/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0.pr3/jackson-annotations-2.9.0.pr3.jar:/home/helmut/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.0.pr3/jackson-core-2.9.0.pr3.jar:/home/helmut/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.0.pr3/jackson-datatype-jsr310-2.9.0.pr3.jar:/home/helmut/.m2/repository/org/jfxtras/jfxtras-all/8.0-r5/jfxtras-all-8.0-r5.jar:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar:/home/helmut/.m2/repository/org/jfxtras/jfxtras-agenda/8.0-r5/jfxtras-agenda-8.0-r5.jar:/home/helmut/.m2/repository/org/jfxtras/jfxtras-controls/8.0-r5/jfxtras-controls-8.0-r5.jar:/home/helmut/.m2/repository/org/jfxtras/jfxtras-common/8.0-r5/jfxtras-common-8.0-r5.jar:/home/helmut/.m2/repository/org/jfxtras/jfxtras-fxml/8.0-r5/jfxtras-fxml-8.0-r5.jar:/home/helmut/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1-m05/javax.ws.rs-api-2.1-m05.jar:/home/helmut/.m2/repository/com/itextpdf/kernel/7.0.2/kernel-7.0.2.jar:/home/helmut/.m2/repository/org/slf4j/slf4j-api/1.7.13/slf4j-api-1.7.13.jar:/home/helmut/.m2/repository/com/itextpdf/io/7.0.2/io-7.0.2.jar:/home/helmut/.m2/repository/com/itextpdf/layout/7.0.2/layout-7.0.2.jar:/home/helmut/.m2/repository/com/itextpdf/forms/7.0.2/forms-7.0.2.jar:/home/helmut/.m2/repository/com/itextpdf/pdfa/7.0.2/pdfa-7.0.2.jar:/home/helmut/.m2/repository/com/itextpdf/sign/7.0.2/sign-7.0.2.jar:/home/helmut/.m2/repository/com/itextpdf/barcodes/7.0.2/barcodes-7.0.2.jar:/home/helmut/.m2/repository/com/itextpdf/hyph/7.0.2/hyph-7.0.2.jar:/home/helmut/.m2/repository/org/jodreports/jodreports-library/3.0.0/jodreports-library-3.0.0.jar:/home/helmut/.m2/repository/commons-io/commons-io/1.4/commons-io-1.4.jar:/home/helmut/.m2/repository/org/freemarker/freemarker/2.3.16/freemarker-2.3.16.jar:/home/helmut/.m2/repository/xom/xom/1.2.5/xom-1.2.5.jar" team_f.client.gui.Client
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:08 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css
May 12, 2017 2:27:11 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-disabled-opacity' while resolving lookups for '-fx-opacity' from rule '*.big-decimal-field:disabled' in stylesheet jar:file:/home/helmut/.m2/repository/org/jfxtras/jfxtras-labs/8.0-r5/jfxtras-labs-8.0-r5.jar!/jfxtras/labs/internal/scene/control/BigDecimalField.css

Process finished with exit code 0

**Comment by obi5747** [comment]
C:\Users\w7pro\.m2\repository\org\jfxtras\jfxtras-labs\8.0-r5\jfxtras-labs-8.0-r5.jar\jfxtras\labs\internal\scene\control\
-->open BigDecimalField.css and change following line at ".big-decimal-field:disabled "

-  -fx-opacity: -fx-disabled-opacity; (this line should be replaced with the next line)

+    -fx-opacity: 0.4;

**Comment by obi5747** [comment]
change  _firstViolinField = new NumberField((Integer) null, 0, Integer.MAX_VALUE);
to   _firstViolinField = new NumberField(0, 0, Integer.MAX_VALUE);

otherwise the increment button will not work until the user enters a number

**Comment by hrh5775** [comment]
> change _firstViolinField = new NumberField((Integer) null, 0, Integer.MAX_VALUE);
> to _firstViolinField = new NumberField(0, 0, Integer.MAX_VALUE);
> 
> otherwise the increment button will not work until the user enters a number

Does call an other constructor which allows double values. Do we want comma separated values for this?

**Comment by hrh5775** [comment]
please create a issue for every new topic

**Comment by hrh5775** [comment]
Ok is a little bit tricky, because we use maven. We should try to override it in numberfield control

**Comment by hrh5775** [comment]
magically fixed due to the help of @obi5747
