### ISSUE TITLE
Editing Person SQL ISSUE

### ISSUE THREAD

**Issue by obi5747** [Nepomuk1999/ConcertMaster#13]
18-May-2017 15:10:36.608 WARN [http-nio-8080-exec-6] org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions SQL Error: 1062, SQLState: 23000
18-May-2017 15:10:36.608 ERROR [http-nio-8080-exec-6] org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions Duplicate entry '153-22' for key 'PRIMARY'
18-May-2017 15:10:36.609 INFO [http-nio-8080-exec-6] org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.release HHH000010: On release of batch it still contained JDBC statements

**Comment by hrh5775** [comment]
not relevant anymore
