### ISSUE TITLE
addEvent bug

### ISSUE THREAD

**Issue by ChristophRheinberger** [Nepomuk1999/ConcertMaster#4]
Hibernate: insert into EventDuty_MusicalWork (alternativeInstrumentation, musicalWork, eventDuty) values (?, ?, ?)

27-Apr-2017 12:52:56.142 ERROR [http-nio-8080-exec-7] org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions Cannot add or update a child row: a foreign key constraint fails (`hrh5775`.`EventDuty_MusicalWork`, CONSTRAINT `EventDuty_MusicalWork_ibfk_2` FOREIGN KEY (`musicalWork`) REFERENCES `MusicalWork` (`musicalWorkID`))
27-Apr-2017 12:52:56.145 ERROR [http-nio-8080-exec-7] org.hibernate.internal.ExceptionMapperStandardImpl.mapManagedFlushFailure HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]

**Comment by hrh5775** [comment]
please add your code snippet or a zipped copy of your current work
