### ISSUE TITLE
Update-Error during publishing Events for August

### ISSUE THREAD

**Issue by obi5747** [Nepomuk1999/ConcertMaster#5]
03-May-2017 10:42:23.779 WARN [http-nio-8080-exec-3] org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions SQL Error: 1205, SQLState: 40001

03-May-2017 10:42:23.780 ERROR [http-nio-8080-exec-3] org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions Lock wait timeout exceeded; try restarting transaction

03-May-2017 10:42:23.783 INFO [http-nio-8080-exec-3] org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.release HHH000010: On release of batch it still contained JDBC statements

**Comment by hrh5775** [comment]
# eventDutyID, name, description, starttime, endtime, eventType, eventStatus, conductor, location, rehearsalFor, defaultPoints, instrumentation
'110', 'Opera Event Test', 'Description', '2017-04-18 19:00:00', '2017-04-18 22:00:00', 'Opera', 'Unpublished', 'Person', 'Fußach', 111, '6', NULL

**Comment by hrh5775** [comment]
not relevant anymore
